apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-check
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: gobinda.com.bd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service1
                port:
                  number: 80
          - path: /nginx2.html
            pathType: Prefix
            backend:
              service:
                name: nginx-service2
                port:
                  number: 80

